creating announcementt
anna-gordiyenko/keksobooking pull request #5
Opened 2021-06-19 07:30 UTC by anna-gordiyenko

I need help

2021-06-25 08:07 UTC, klymenko-oleksandr requested changes

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/main.js
> +import {similarListFragment} from './popup';
Указать расширение файла `./popup.js` -- возможно переименовать

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/main.js
> +import {similarListFragment} from './popup';
Из (на данный момент) `popup.js` ты должна 
1. импортировать фрагмент, который будет в себе содержать разметку с несколькими (или 1-м) объявлениями и в разметке должны быть актуальные данные, которые ты берешь из своих сгенерированных данных.
2. Уже в файле `main.js` сделай вывод фрагмента к примеру внутрь "дива" с картой, чтобы увидеть результат

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/popup.js
> +import {createAnnouncement} from './data.js';
Помни что это функция, которая возвращает объект с объявлением.
Можно  сделать в этом файле переменную с кол-вом объяв, и сделать цикл по этому кол-ву

```javascript
const ITEMS_COUNT = 3;
const itemsArray = [];

for (let idx = 0; idx < ITEMS_COUNT; idx++) {
  // создаем объяву с помощью ф-ции createAnnouncement
  // добавляем новую объяву в массив itemsArray
}
```
Теперь у нас есть массив с объявами -- запомнили

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/popup.js
> +const similarListElement = document.querySelector('.map');
это просто `mapContainer` или `mapWrp` -- от слова wrapper

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/popup.js
> +document.querySelector('.checkbox').classList.remove('visually-hidden');
Это нам не нужно

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/popup.js
> +const similarListFragment = document.createDocumentFragment();
Лучше назвать `announcementsFragment` -- в множественном числе, мол мы туда будем ложить несколько объяв

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/popup.js
> +similarAnnouncement.forEach(({title, address, price, type, rooms, guests, checkin, checkout, features, description, photos, avatar}) => {
Деструктуризация не нужна, раз мы используем все свойства объекта + там на верхнем уровне всего 3 свойства

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/popup.js
> +    announcementElement.querySelector('.popup__photo').img.src = photos[i];
У HTMLElement `img` уже есть свойство `src` -- не нужно доп писать `.img`

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/popup.js
> +export {similarListFragment};
Попробуй экспортировать фрагмент, который будет в себе содержать разметку с несколькими (или 1-м) объявлениями, у тебя сейчас это `similarListFragment `, но я предложил назвать его `announcementsFragment `

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/popup.js
> +similarAnnouncement.forEach(({title, address, price, type, rooms, guests, checkin, checkout, features, description, photos, avatar}) => {
Вместо это го цикла, я бы предложил написать функцию, которая будет принимать html элемент(пустой) и объект объявления(данные) и возвращать элемент уже с реальными данными:
```javascript
function createAnnouncementMarkup(element, announcement) {
  // тут мы находим нужные элементы в "целом" элементе и заполняем их данными
  // к примеру находим див для заголовка
  // element.querySelector('.popup__title').textContent = announcement.offer.title; -- тут нужно придумать как
  // сделать так, что бы если данных в объекте нет, то удалять див из разметки
  // и так заполняем элемент всеми данными
  // В конце возвращаем элемент!
}
```

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/popup.js
> +const similarAnnouncementTemplate = document.querySelector('#card')
Лучше просто назвать `announcementTemplate`

2021-06-25 08:07 UTC, klymenko-oleksandr commented on js/popup.js
> +similarAnnouncement.forEach(({title, address, price, type, rooms, guests, checkin, checkout, features, description, photos, avatar}) => {
Затем нам остается:
1. пройтись по нашему массиву объектов с объявами `itemsArray `
```javascript
  // один из вариантов
  itemsArray.forEach( item => { // в item у нас лежит объект с объявой
    // 1. создаем элемент 
    const announcementElement = announcementTemplate.cloneNode(true);
    // 2. наполняем разметкой
    const announcement = createAnnouncementMarkup(announcementElement, item);
    // 3. заносим наш элемент с данными в наш "контейнер-фрагмент"
    announcementsFragment.appendChild(announcement);
  } );
  
  // 2. Теперь у нас есть фрагмент с нашей разметкой с данными
  // и мы можем его экспортировать из данного файла,
  // а уже в `main.js` положить его в карту к примеру
```

2021-07-04 14:31 UTC, klymenko-oleksandr approved these changes
1. Ты в файле `announcement.js` делаешь `similarListElement.appendChild(announcementsFragment);` -- что уже рендерит на страницу если не ошибаюсь твои объявления, а затем из этого же файла экспортируешь `announcementsFragment`, который потом снова добавляешь на страницу, только уже в файле `main.js` => `mapCanva.appendChild(announcementsFragment);`
Думаю что стоит один вывод оставить / но это не критично, так как след задания это все исправят)

2021-07-04 14:31 UTC, klymenko-oleksandr commented
Убери мой 2й аккаунт из проверяющих и можешь принимать ПР

2021-07-05 11:49 UTC, anna-gordiyenko commented
> 1. Ты в файле `announcement.js` делаешь `similarListElement.appendChild(announcementsFragment);` -- что уже рендерит на страницу если не ошибаюсь твои объявления, а затем из этого же файла экспортируешь `announcementsFragment`, который потом снова добавляешь на страницу, только уже в файле `main.js` => `mapCanva.appendChild(announcementsFragment);`
>    Думаю что стоит один вывод оставить / но это не критично, так как след задания это все исправят)

правильно первый раз чтобы всё подобавлять, а второй чтобы попробовать временно вывести посмотреть.

2021-07-05 11:50 UTC, merged